---
# tasks file for 07-join-master-nodes
#- name: test "{{ansible_eth0.ipv4.address}}"

- name: copy kubeadm command in servers
  copy:
   src: /tmp/kubeadmin-init
   dest: /tmp/kubeadmin-init.sh
   owner: ansible
   group: docker
   mode: "0777"

- name: remove useless characters in the command
  replace:
    path: /tmp/kubeadmin-init.sh
    regexp: '\\ '
    replace: ' '
    backup: yes

- name: remove useless characters in the command
  replace:
    path: /tmp/kubeadmin-init.sh
    regexp: '  kubeadm'
    replace: 'kubeadm'
    backup: yes

- name: run Kubeadm join command
  become: true
  command: sh /tmp/kubeadmin-init.sh
  register: result

- debug: var=result.stdout